/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CartCard: typeof import('./src/components/shared/CartCard.vue')['default']
    Divide: typeof import('./src/components/shared/Divide.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    IconAddToCart: typeof import('./src/components/icons/IconAddToCart.vue')['default']
    IconCalculator: typeof import('./src/components/icons/IconCalculator.vue')['default']
    IconCart: typeof import('./src/components/icons/IconCart.vue')['default']
    IconLoading: typeof import('./src/components/icons/IconLoading.vue')['default']
    IconMinus: typeof import('./src/components/icons/IconMinus.vue')['default']
    IconPlus: typeof import('./src/components/icons/IconPlus.vue')['default']
    IconSearch: typeof import('./src/components/icons/IconSearch.vue')['default']
    IconTrash: typeof import('./src/components/icons/IconTrash.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PaymentSheet: typeof import('./src/components/PaymentSheet.vue')['default']
    ProductCard: typeof import('./src/components/shared/ProductCard.vue')['default']
    Products: typeof import('./src/components/Products.vue')['default']
    QtyButton: typeof import('./src/components/shared/QtyButton.vue')['default']
  }
}
