/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cart: typeof import('./src/components/shared/Cart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconAddToCart: typeof import('./src/components/icons/IconAddToCart.vue')['default']
    IconCart: typeof import('./src/components/icons/IconCart.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconLoading: typeof import('./src/components/icons/IconLoading.vue')['default']
    IconSearch: typeof import('./src/components/icons/IconSearch.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PaymentSheet: typeof import('./src/components/PaymentSheet.vue')['default']
    Products: typeof import('./src/components/Products.vue')['default']
    Search: typeof import('./src/components/icons/Search.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
